#!/bin/bash

publish_to_maven() {
    begin Maven
    [ ! -d "${1:-}" ] && error "Require target directory as first parameter"
    [ -z "${GITHUB_TOKEN:-}" ] && error "GITHUB_TOKEN required"
    [ -z "${GITHUB_REPOSITORY:-}" ] && error "GITHUB_REPOSITORY required"
    GITHUB_REPOSITORY=$(echo "${GITHUB_REPOSITORY:-}" | tr '[:upper:]' '[:lower:]')

    cd "${1:-}" || exit

    pom="$(find * -name "*.pom")"
    jar="${pom/.pom/.jar}"

    upload "${jar}"
    upload "${pom}"

    complete
}

upload() {
  local file="$1"
  curl -X PUT \
    "https://maven.pkg.github.com/${GITHUB_REPOSITORY:-}/${file}" \
    -H "Authorization: token ${GITHUB_TOKEN:-}" \
    --upload-file "${file}" --fail -vvv || exit
}
