#!/bin/bash

publish_to_maven() {
    begin Maven
    require_dir "${1:-}"
    require GITHUB_TOKEN
    require GITHUB_REPOSITORY
    GITHUB_REPOSITORY=$(echo "${GITHUB_REPOSITORY:-}" | tr '[:upper:]' '[:lower:]')

    cd "${1:-}" || exit

    pom="$(find * -name "*.pom")"
    jar="${pom/.pom/.jar}"

    upload "${jar}"
    upload "${pom}"

    complete
}

upload() {
  local file="$1"
  local cmd

  cmd=(curl -X PUT)
  cmd+=("https://maven.pkg.github.com/${GITHUB_REPOSITORY:-}/${file}")
  cmd+=(-H "'Authorization: token ${GITHUB_TOKEN:-}'")
  cmd+=(--upload-file "${file}" --fail --silent --show-error)
  if [[ "${DEBUG}" = true ]]; then
    cmd+=(-vvv)
  fi

  eval "${cmd[@]}" || exit
}
