#!/bin/bash

publish_to_npm() {
    begin npm
    require_dir "${1:-}"
    require NPM_TOKEN

    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

    cmd=(npm publish)
    if [[ "${DEBUG}" = true ]]; then
        cmd+=(--verbose)
    fi
    cmd+=("$1")

    eval "${cmd[@]}"

    complete
}
