#!/bin/bash

publish_to_nuget() {
    begin NuGet
    [ -z "${1:-}" ] && error "Require target directory as first parameter"
    [ -z "${NUGET_TOKEN:-}" ] && error "NUGET_TOKEN required"

    dotnet nuget push "$1" -k "${NUGET_TOKEN}" -s https://api.nuget.org/v3/index.json --skip-duplicate

    complete
}
