#!/bin/bash

publish_to_pypi() {
    begin PyPI
    [ -z "${1:-}" ] && error "Require target directory as first parameter"
    [ -z "${PYPI_TOKEN:-}" ] && error "PYPI_TOKEN required"

    cat <<EOF > ~/.pypirc
[pypi]
username = __token__
password = ${PYPI_TOKEN}
EOF
    twine upload --skip-existing "$1"

    complete
}
