#!/bin/bash

publish_to_pypi() {
    begin PyPI
    require_dir "${1:-}"
    require PYPI_TOKEN

    cat <<EOF > ~/.pypirc
[pypi]
username = __token__
password = ${PYPI_TOKEN}
EOF

    cmd=(twine upload --skip-existing)
    if [[ "${DEBUG}" = true ]]; then
        cmd+=(--verbose)
    fi

    if [ -n "${PYPI_OPTIONS}" ]; then
        cmd+=("${PYPI_OPTIONS}")
    fi

    cmd+=("$1/*")

    eval "${cmd[@]}"

    complete
}
